Tests/evolutionary classes
Civil-Data/Grupp24 pull request #22
Opened 2024-09-13 09:29 UTC by JoelScarinius

Add tests for crossover class.

2024-09-15 08:54 UTC, Linkan42 commented on tests/evolutionary_classes/test_selection.py
> +#this test do not end, unclear why
In rank(...): `while len(parents) < 2:  # 2 parents`

It will always select two parents. If population is only 1, it will get stuck in this while loop

2024-09-15 09:06 UTC, Linkan42 commented on tests/evolutionary_classes/test_fitness.py
> +    genome = Genome([MockPerson(False), MockPerson(False)])
sir this is illegal. Genome constructor takes a List[int] as arg

2024-09-15 09:07 UTC, OskarSundberg reviewed
![image](https://github.com/user-attachments/assets/0a3f41eb-5724-4018-91f1-599d7b3a0fb0)

2024-09-15 09:10 UTC, Linkan42 commented on tests/evolutionary_classes/test_fitness.py
> +class MockPerson:
I fail to see the reason to use a mock. Genome inherently uses Person, I doubt a mock will work, but maybe I'm wrong 🤔

2024-09-15 09:11 UTC, Linkan42 commented on tests/evolutionary_classes/test_mutation.py
> +    assert len(genome.genome) == 7
Nice, but checking that the new floor is also a valid floor would be even nicer 😉

2024-09-15 09:17 UTC, Linkan42 commented on tests/evolutionary_classes/test_mutation.py
> +    assert genome.genome != [1, 2, 3, 4, 5, 6]
Checking that the length doesn't change would also be quite nice

2024-09-15 09:23 UTC, Linkan42 commented on tests/evolutionary_classes/test_populate.py
> +    assert len(population) == data.POPULATION_SIZE
Consider also checking that the floors are valid in the genomes

2024-09-15 09:26 UTC, Linkan42 commented on tests/evolutionary_classes/test_selection.py
> +    parents = Selection.rank(population)
highly illegal. Selection algorithms by definition takes List[Genome] as arg

2024-09-15 09:37 UTC, Linkan42 requested changes
heed my comments

2024-09-15 13:36 UTC, JoelScarinius commented on tests/evolutionary_classes/test_selection.py
> +    parents = Selection.rank(population)
Yes the population is a List of Mockgenomes?

2024-09-17 17:44 UTC, Linkan42 approved these changes
i approve

2024-09-17 17:44 UTC, merged