Small changes and correction to the introduction
Civil-Data/Grupp24 pull request #47
Opened 2024-09-22 16:05 UTC by samwalle

2024-09-23 06:07 UTC, OskarSundberg approved these changes
LGTM

2024-09-23 06:56 UTC, JoelScarinius requested changes
I like the changes to the text.

There are some spelling errors that would be awesome if you fix and then push again. 

If you don't use a spellchecker I can show some nice tools to help you out.

2024-09-23 17:13 UTC, Linkan42 requested changes

2024-09-23 17:13 UTC, Linkan42 commented on report/Introduction.tex
> +In large buildings with a lot of floors, efficient elevators are crucial for managing traffick and must serve every one in a reasonable time.
actually, it is spelled "traffic"

2024-09-24 11:23 UTC, OskarSundberg commented
Closing this PR because I'm going to fix more stuff and to avoid more trouble.

2024-09-24 11:23 UTC, closed without merging