A first atempt at lower and upper bound, there is for sure some logic…
Civil-Data/Grupp24 pull request #67
Opened 2024-09-30 05:47 UTC by OskarSundberg

…al problem in this. It's to late for this kind of work tbh.

2024-09-30 08:53 UTC, Linkan42 requested changes

2024-09-30 08:53 UTC, Linkan42 commented on report/lowerbound.tex
> +Prof:
Proof

2024-09-30 08:53 UTC, Linkan42 commented on report/lowerbound.tex
> +A building whit F = 3, N = 1, the person is on floor 0 and like to go to floor 2. The elevator picks up the person but never goes to floor 2, instead the elevator moves between floor zero and floor o
with

2024-09-30 08:53 UTC, Linkan42 commented on report/lowerbound.tex
> +Assumption III: The elevator has the capacity of N.
You define N as number of persons in building, floor and elevator capacity ??

2024-09-30 08:53 UTC, Linkan42 commented on report/lowerbound.tex
> +Simple case: A building with F = 2 and N = 1, were the person needs to move for floor zero to floor one. It is trivial to see that the best solution is for the elevator to take one person from floor
where

2024-09-30 17:51 UTC, JoelScarinius commented
Need to run git pull origin main

2024-10-01 07:18 UTC, JoelScarinius approved these changes
LGTM!

2024-10-01 08:20 UTC, Linkan42 approved these changes

2024-10-01 08:20 UTC, merged